/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FacilitiesRouteImport } from './routes/facilities'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HighSchoolChekkapalliRouteImport } from './routes/high-school-chekkapalli'
import { Route as HowToChooseTheRightEnglishMediumSchoolInChekkapalliRouteImport } from './routes/how-to-choose-the-right-english-medium-school-in-chekkapalli'
import { Route as ImportanceOfActivityBasedLearningRouteImport } from './routes/importance-of-activity-based-learning'
import { Route as NurserySchoolChekkapalliRouteImport } from './routes/nursery-school-chekkapalli'
import { Route as PrimarySchoolChekkapalliRouteImport } from './routes/primary-school-chekkapalli'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SchoolTransportChekkapalliRouteImport } from './routes/school-transport-chekkapalli'
import { Route as AcademicsStageRouteImport } from './routes/academics_.$stage'
import { Route as AdminDashboardRouteImport } from './routes/admin_.dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesRoute = FacilitiesRouteImport.update({
  id: '/facilities',
  path: '/facilities',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HighSchoolChekkapalliRoute = HighSchoolChekkapalliRouteImport.update({
  id: '/high-school-chekkapalli',
  path: '/high-school-chekkapalli',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToChooseTheRightEnglishMediumSchoolInChekkapalliRoute =
  HowToChooseTheRightEnglishMediumSchoolInChekkapalliRouteImport.update({
    id: '/how-to-choose-the-right-english-medium-school-in-chekkapalli',
    path: '/how-to-choose-the-right-english-medium-school-in-chekkapalli',
    getParentRoute: () => rootRouteImport,
  } as any)
const ImportanceOfActivityBasedLearningRoute =
  ImportanceOfActivityBasedLearningRouteImport.update({
    id: '/importance-of-activity-based-learning',
    path: '/importance-of-activity-based-learning',
    getParentRoute: () => rootRouteImport,
  } as any)
const NurserySchoolChekkapalliRoute =
  NurserySchoolChekkapalliRouteImport.update({
    id: '/nursery-school-chekkapalli',
    path: '/nursery-school-chekkapalli',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrimarySchoolChekkapalliRoute =
  PrimarySchoolChekkapalliRouteImport.update({
    id: '/primary-school-chekkapalli',
    path: '/primary-school-chekkapalli',
    getParentRoute: () => rootRouteImport,
  } as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolTransportChekkapalliRoute =
  SchoolTransportChekkapalliRouteImport.update({
    id: '/school-transport-chekkapalli',
    path: '/school-transport-chekkapalli',
    getParentRoute: () => rootRouteImport,
  } as any)
const AcademicsStageRoute = AcademicsStageRouteImport.update({
  id: '/academics_/$stage',
  path: '/academics/$stage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin_/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/high-school-chekkapalli': typeof HighSchoolChekkapalliRoute
  '/how-to-choose-the-right-english-medium-school-in-chekkapalli': typeof HowToChooseTheRightEnglishMediumSchoolInChekkapalliRoute
  '/importance-of-activity-based-learning': typeof ImportanceOfActivityBasedLearningRoute
  '/nursery-school-chekkapalli': typeof NurserySchoolChekkapalliRoute
  '/primary-school-chekkapalli': typeof PrimarySchoolChekkapalliRoute
  '/resources': typeof ResourcesRoute
  '/school-transport-chekkapalli': typeof SchoolTransportChekkapalliRoute
  '/academics/$stage': typeof AcademicsStageRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/high-school-chekkapalli': typeof HighSchoolChekkapalliRoute
  '/how-to-choose-the-right-english-medium-school-in-chekkapalli': typeof HowToChooseTheRightEnglishMediumSchoolInChekkapalliRoute
  '/importance-of-activity-based-learning': typeof ImportanceOfActivityBasedLearningRoute
  '/nursery-school-chekkapalli': typeof NurserySchoolChekkapalliRoute
  '/primary-school-chekkapalli': typeof PrimarySchoolChekkapalliRoute
  '/resources': typeof ResourcesRoute
  '/school-transport-chekkapalli': typeof SchoolTransportChekkapalliRoute
  '/academics/$stage': typeof AcademicsStageRoute
  '/admin/dashboard': typeof AdminDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admin': typeof AdminRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/facilities': typeof FacilitiesRoute
  '/gallery': typeof GalleryRoute
  '/high-school-chekkapalli': typeof HighSchoolChekkapalliRoute
  '/how-to-choose-the-right-english-medium-school-in-chekkapalli': typeof HowToChooseTheRightEnglishMediumSchoolInChekkapalliRoute
  '/importance-of-activity-based-learning': typeof ImportanceOfActivityBasedLearningRoute
  '/nursery-school-chekkapalli': typeof NurserySchoolChekkapalliRoute
  '/primary-school-chekkapalli': typeof PrimarySchoolChekkapalliRoute
  '/resources': typeof ResourcesRoute
  '/school-transport-chekkapalli': typeof SchoolTransportChekkapalliRoute
  '/academics_/$stage': typeof AcademicsStageRoute
  '/admin_/dashboard': typeof AdminDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admin'
    | '/admissions'
    | '/contact'
    | '/facilities'
    | '/gallery'
    | '/high-school-chekkapalli'
    | '/how-to-choose-the-right-english-medium-school-in-chekkapalli'
    | '/importance-of-activity-based-learning'
    | '/nursery-school-chekkapalli'
    | '/primary-school-chekkapalli'
    | '/resources'
    | '/school-transport-chekkapalli'
    | '/academics/$stage'
    | '/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/admin'
    | '/admissions'
    | '/contact'
    | '/facilities'
    | '/gallery'
    | '/high-school-chekkapalli'
    | '/how-to-choose-the-right-english-medium-school-in-chekkapalli'
    | '/importance-of-activity-based-learning'
    | '/nursery-school-chekkapalli'
    | '/primary-school-chekkapalli'
    | '/resources'
    | '/school-transport-chekkapalli'
    | '/academics/$stage'
    | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admin'
    | '/admissions'
    | '/contact'
    | '/facilities'
    | '/gallery'
    | '/high-school-chekkapalli'
    | '/how-to-choose-the-right-english-medium-school-in-chekkapalli'
    | '/importance-of-activity-based-learning'
    | '/nursery-school-chekkapalli'
    | '/primary-school-chekkapalli'
    | '/resources'
    | '/school-transport-chekkapalli'
    | '/academics_/$stage'
    | '/admin_/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdminRoute: typeof AdminRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  FacilitiesRoute: typeof FacilitiesRoute
  GalleryRoute: typeof GalleryRoute
  HighSchoolChekkapalliRoute: typeof HighSchoolChekkapalliRoute
  HowToChooseTheRightEnglishMediumSchoolInChekkapalliRoute: typeof HowToChooseTheRightEnglishMediumSchoolInChekkapalliRoute
  ImportanceOfActivityBasedLearningRoute: typeof ImportanceOfActivityBasedLearningRoute
  NurserySchoolChekkapalliRoute: typeof NurserySchoolChekkapalliRoute
  PrimarySchoolChekkapalliRoute: typeof PrimarySchoolChekkapalliRoute
  ResourcesRoute: typeof ResourcesRoute
  SchoolTransportChekkapalliRoute: typeof SchoolTransportChekkapalliRoute
  AcademicsStageRoute: typeof AcademicsStageRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities': {
      id: '/facilities'
      path: '/facilities'
      fullPath: '/facilities'
      preLoaderRoute: typeof FacilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/high-school-chekkapalli': {
      id: '/high-school-chekkapalli'
      path: '/high-school-chekkapalli'
      fullPath: '/high-school-chekkapalli'
      preLoaderRoute: typeof HighSchoolChekkapalliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-choose-the-right-english-medium-school-in-chekkapalli': {
      id: '/how-to-choose-the-right-english-medium-school-in-chekkapalli'
      path: '/how-to-choose-the-right-english-medium-school-in-chekkapalli'
      fullPath: '/how-to-choose-the-right-english-medium-school-in-chekkapalli'
      preLoaderRoute: typeof HowToChooseTheRightEnglishMediumSchoolInChekkapalliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importance-of-activity-based-learning': {
      id: '/importance-of-activity-based-learning'
      path: '/importance-of-activity-based-learning'
      fullPath: '/importance-of-activity-based-learning'
      preLoaderRoute: typeof ImportanceOfActivityBasedLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nursery-school-chekkapalli': {
      id: '/nursery-school-chekkapalli'
      path: '/nursery-school-chekkapalli'
      fullPath: '/nursery-school-chekkapalli'
      preLoaderRoute: typeof NurserySchoolChekkapalliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primary-school-chekkapalli': {
      id: '/primary-school-chekkapalli'
      path: '/primary-school-chekkapalli'
      fullPath: '/primary-school-chekkapalli'
      preLoaderRoute: typeof PrimarySchoolChekkapalliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-transport-chekkapalli': {
      id: '/school-transport-chekkapalli'
      path: '/school-transport-chekkapalli'
      fullPath: '/school-transport-chekkapalli'
      preLoaderRoute: typeof SchoolTransportChekkapalliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics_/$stage': {
      id: '/academics_/$stage'
      path: '/academics/$stage'
      fullPath: '/academics/$stage'
      preLoaderRoute: typeof AcademicsStageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/dashboard': {
      id: '/admin_/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdminRoute: AdminRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  FacilitiesRoute: FacilitiesRoute,
  GalleryRoute: GalleryRoute,
  HighSchoolChekkapalliRoute: HighSchoolChekkapalliRoute,
  HowToChooseTheRightEnglishMediumSchoolInChekkapalliRoute:
    HowToChooseTheRightEnglishMediumSchoolInChekkapalliRoute,
  ImportanceOfActivityBasedLearningRoute:
    ImportanceOfActivityBasedLearningRoute,
  NurserySchoolChekkapalliRoute: NurserySchoolChekkapalliRoute,
  PrimarySchoolChekkapalliRoute: PrimarySchoolChekkapalliRoute,
  ResourcesRoute: ResourcesRoute,
  SchoolTransportChekkapalliRoute: SchoolTransportChekkapalliRoute,
  AcademicsStageRoute: AcademicsStageRoute,
  AdminDashboardRoute: AdminDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
